window.CPCS = [
  {
    "numero": "00",
    "nome": "Estrutura Conceitual para Relatório Financeiro",
    "pdf": "./pdf/CPC-00-R2-Estrutura-Conceitual.pdf",
    "resumo": "./resumos/cpc00-resumo.html",
    "mapa": "./mapas/cpc00-mapa.html",
    "casos": "./casos/cpc00-casos.html",
    "flashcards": "./resumos/cpc00-flashcards.html",
    "dicionario": "./resumos/cpc00-dicionario.html",
    "quizzes": "./quizzes/cpc00-index.html",
    "comentarios": "./comentarios/cpc00-questoes.html",
    "simulado": "./quizzes/cpc00-simulado.html",
    "palavras": [
      "estrutura conceitual",
      "ativo",
      "passivo",
      "receita",
      "despesa",
      "relevância",
      "materialidade",
      "mensuração"
    ]
  },

  {
    "numero": "01",
    "nome": "Redução ao Valor Recuperável de Ativos",
    "ativo": true,
    "pdf": "./pdf/CPC-01-R1-Reducao-Valor-Recuperavel-Ativos.pdf",
    "resumo": "./resumos/cpc01-resumo.html",
    "mapa": "./mapas/cpc01-mapa.html",
    "casos": "./casos/cpc01-casos.html",
    "dicionario": "./resumos/cpc01-dicionario.html",
    "flashcards": "./resumos/cpc01-flashcards.html",
    "quizzes": "./quizzes/cpc01-index.html",
    "comentarios": "./comentarios/cpc01-questoes.html",
    "banco": "./questoes/cpc01-banco.html",
    "simulado": "./quizzes/cpc01-simulado.html",
    "macetes": "./resumos/cpc01-macetes.html",
    "erros": "./resumos/cpc01-erros.html",
    "checklist": "./resumos/cpc01-checklist.html",
    "palavras": ["impairment", "valor recuperável", "valor em uso", "valor justo líquido", "perda por desvalorização", "unidade geradora de caixa", "ugc", "goodwill", "reversão"]
  },
  {
    "numero": "02",
    "nome": "Efeitos das Mudanças nas Taxas de Câmbio e Conversão de Demonstrações Contábeis",
    "ativo": true,
    "pdf": "./pdf/CPC-02-R2-Efeitos-Taxas-Cambio-Conversao.pdf",
    "resumo": "./resumos/cpc02-resumo.html",
    "mapa": "./mapas/cpc02-mapa.html",
    "casos": "./casos/cpc02-casos.html",
    "dicionario": "./resumos/cpc02-dicionario.html",
    "flashcards": "./resumos/cpc02-flashcards.html",
    "quizzes": "./quizzes/cpc02-index.html",
    "comentarios": "./comentarios/cpc02-questoes.html",
    "banco": "./questoes/cpc02-banco.html",
    "simulado": "./quizzes/cpc02-simulado.html",
    "macetes": "./resumos/cpc02-macetes.html",
    "erros": "./resumos/cpc02-erros.html",
    "checklist": "./resumos/cpc02-checklist.html",
    "palavras": ["câmbio", "moeda funcional", "moeda estrangeira", "taxa de fechamento", "variação cambial", "conversão", "entidade no exterior", "item monetário", "conversibilidade"]
  },
  {
    "numero": "03",
    "nome": "Demonstração dos Fluxos de Caixa",
    "ativo": true,
    "pdf": "./pdf/CPC-03-R2-Demonstracao-Fluxos-Caixa.pdf",
    "resumo": "./resumos/cpc03-resumo.html",
    "mapa": "./mapas/cpc03-mapa.html",
    "casos": "./casos/cpc03-casos.html",
    "dicionario": "./resumos/cpc03-dicionario.html",
    "flashcards": "./resumos/cpc03-flashcards.html",
    "quizzes": "./quizzes/cpc03-index.html",
    "comentarios": "./comentarios/cpc03-questoes.html",
    "banco": "./questoes/cpc03-banco.html",
    "simulado": "./quizzes/cpc03-simulado.html",
    "macetes": "./resumos/cpc03-macetes.html",
    "erros": "./resumos/cpc03-erros.html",
    "checklist": "./resumos/cpc03-checklist.html",
    "palavras": ["dfc", "fluxo de caixa", "método direto", "método indireto", "operacional", "investimento", "financiamento", "risco sacado"]
  },
  {
    "numero": "04",
    "nome": "Ativo Intangível",
    "ativo": true,
    "pdf": "./pdf/CPC-04-R1-Ativo-Intangivel.pdf",
    "resumo": "./resumos/cpc04-resumo.html",
    "mapa": "./mapas/cpc04-mapa.html",
    "casos": "./casos/cpc04-casos.html",
    "dicionario": "./resumos/cpc04-dicionario.html",
    "flashcards": "./resumos/cpc04-flashcards.html",
    "quizzes": "./quizzes/cpc04-index.html",
    "comentarios": "./comentarios/cpc04-questoes.html",
    "banco": "./questoes/cpc04-banco.html",
    "simulado": "./quizzes/cpc04-simulado.html",
    "macetes": "./resumos/cpc04-macetes.html",
    "erros": "./resumos/cpc04-erros.html",
    "checklist": "./resumos/cpc04-checklist.html",
    "palavras": ["intangível", "pesquisa", "desenvolvimento", "amortização", "vida útil", "goodwill", "website", "software", "patente", "marca"]
  },
  {
    "numero": "06",
    "nome": "Arrendamentos",
    "ativo": true,
    "pdf": "./pdf/CPC-06-R2-Arrendamentos.pdf",
    "resumo": "./resumos/cpc06-resumo.html",
    "mapa": "./mapas/cpc06-mapa.html",
    "casos": "./casos/cpc06-casos.html",
    "dicionario": "./resumos/cpc06-dicionario.html",
    "flashcards": "./resumos/cpc06-flashcards.html",
    "quizzes": "./quizzes/cpc06-index.html",
    "comentarios": "./comentarios/cpc06-questoes.html",
    "banco": "./questoes/cpc06-banco.html",
    "simulado": "./quizzes/cpc06-simulado.html",
    "macetes": "./resumos/cpc06-macetes.html",
    "erros": "./resumos/cpc06-erros.html",
    "checklist": "./resumos/cpc06-checklist.html",
    "palavras": ["arrendamento", "ifrs 16", "direito de uso", "passivo de arrendamento", "arrendatario", "arrendador", "curto prazo", "baixo valor", "sale and leaseback"]
  },
  {
    "numero": "09",
    "nome": "Demonstração do Valor Adicionado",
    "ativo": true,
    "pdf": "./pdf/CPC-09-R1-Demonstracao-Valor-Adicionado.pdf",
    "resumo": "./resumos/cpc09-resumo.html",
    "mapa": "./mapas/cpc09-mapa.html",
    "casos": "./casos/cpc09-casos.html",
    "dicionario": "./resumos/cpc09-dicionario.html",
    "flashcards": "./resumos/cpc09-flashcards.html",
    "quizzes": "./quizzes/cpc09-index.html",
    "comentarios": "./comentarios/cpc09-questoes.html",
    "banco": "./questoes/cpc09-banco.html",
    "simulado": "./quizzes/cpc09-simulado.html",
    "macetes": "./resumos/cpc09-macetes.html",
    "erros": "./resumos/cpc09-erros.html",
    "checklist": "./resumos/cpc09-checklist.html",
    "palavras": ["dva", "valor adicionado", "riqueza", "insumos de terceiros", "distribuição da riqueza"]
  },
  {
    "numero": "16",
    "nome": "Estoques",
    "ativo": true,
    "pdf": "./pdf/CPC-16-R1-Estoques.pdf",
    "resumo": "./resumos/cpc16-resumo.html",
    "mapa": "./mapas/cpc16-mapa.html",
    "casos": "./casos/cpc16-casos.html",
    "dicionario": "./resumos/cpc16-dicionario.html",
    "flashcards": "./resumos/cpc16-flashcards.html",
    "quizzes": "./quizzes/cpc16-index.html",
    "comentarios": "./comentarios/cpc16-questoes.html",
    "banco": "./questoes/cpc16-banco.html",
    "simulado": "./quizzes/cpc16-simulado.html",
    "macetes": "./resumos/cpc16-macetes.html",
    "erros": "./resumos/cpc16-erros.html",
    "checklist": "./resumos/cpc16-checklist.html",
    "palavras": ["estoques", "custo", "valor realizável líquido", "vrl", "peps", "custo médio", "capacidade normal", "desperdício", "obsolescência"]
  },
  {
    "numero": "18",
    "nome": "Investimento em Coligada e em Empreendimento Controlado em Conjunto",
    "ativo": true,
    "pdf": "./pdf/CPC-18-R3-Coligadas-Joint-Ventures.pdf",
    "resumo": "./resumos/cpc18-resumo.html",
    "mapa": "./mapas/cpc18-mapa.html",
    "casos": "./casos/cpc18-casos.html",
    "dicionario": "./resumos/cpc18-dicionario.html",
    "flashcards": "./resumos/cpc18-flashcards.html",
    "quizzes": "./quizzes/cpc18-index.html",
    "comentarios": "./comentarios/cpc18-questoes.html",
    "banco": "./questoes/cpc18-banco.html",
    "simulado": "./quizzes/cpc18-simulado.html",
    "macetes": "./resumos/cpc18-macetes.html",
    "erros": "./resumos/cpc18-erros.html",
    "checklist": "./resumos/cpc18-checklist.html",
    "palavras": ["coligada", "influência significativa", "mep", "equivalência patrimonial", "joint venture", "upstream", "downstream", "goodwill", "impairment"]
  },
  {
    "numero": "23",
    "nome": "Políticas Contábeis, Mudança de Estimativa e Retificação de Erro",
    "ativo": true,
    "pdf": "./pdf/CPC-23-Politicas-Estimativas-Erros.pdf",
    "resumo": "./resumos/cpc23-resumo.html",
    "mapa": "./mapas/cpc23-mapa.html",
    "casos": "./casos/cpc23-casos.html",
    "dicionario": "./resumos/cpc23-dicionario.html",
    "flashcards": "./resumos/cpc23-flashcards.html",
    "quizzes": "./quizzes/cpc23-index.html",
    "comentarios": "./comentarios/cpc23-questoes.html",
    "banco": "./questoes/cpc23-banco.html",
    "simulado": "./quizzes/cpc23-simulado.html",
    "macetes": "./resumos/cpc23-macetes.html",
    "erros": "./resumos/cpc23-erros.html",
    "checklist": "./resumos/cpc23-checklist.html",
    "palavras": ["política contábil", "estimativa contábil", "erro", "retrospectiva", "prospectiva", "reapresentação", "impraticabilidade", "materialidade"]
  },
  {
    "numero": "24",
    "nome": "Evento Subsequente",
    "ativo": true,
    "pdf": "./pdf/CPC-24-Evento-Subsequente.pdf",
    "resumo": "./resumos/cpc24-resumo.html",
    "mapa": "./mapas/cpc24-mapa.html",
    "casos": "./casos/cpc24-casos.html",
    "dicionario": "./resumos/cpc24-dicionario.html",
    "flashcards": "./resumos/cpc24-flashcards.html",
    "quizzes": "./quizzes/cpc24-index.html",
    "comentarios": "./comentarios/cpc24-questoes.html",
    "banco": "./questoes/cpc24-banco.html",
    "simulado": "./quizzes/cpc24-simulado.html",
    "macetes": "./resumos/cpc24-macetes.html",
    "erros": "./resumos/cpc24-erros.html",
    "checklist": "./resumos/cpc24-checklist.html",
    "palavras": ["evento subsequente", "ajuste", "não ajuste", "data de autorização", "dividendos", "continuidade", "divulgação"]
  },
  {
    "numero": "25",
    "nome": "Provisões, Passivos Contingentes e Ativos Contingentes",
    "ativo": true,
    "pdf": "./pdf/CPC-25-Provisoes-Contingencias.pdf",
    "resumo": "./resumos/cpc25-resumo.html",
    "mapa": "./mapas/cpc25-mapa.html",
    "casos": "./casos/cpc25-casos.html",
    "dicionario": "./resumos/cpc25-dicionario.html",
    "flashcards": "./resumos/cpc25-flashcards.html",
    "quizzes": "./quizzes/cpc25-index.html",
    "comentarios": "./comentarios/cpc25-questoes.html",
    "banco": "./questoes/cpc25-banco.html",
    "simulado": "./quizzes/cpc25-simulado.html",
    "macetes": "./resumos/cpc25-macetes.html",
    "erros": "./resumos/cpc25-erros.html",
    "checklist": "./resumos/cpc25-checklist.html",
    "palavras": ["provisão", "passivo contingente", "ativo contingente", "obrigação presente", "contrato oneroso", "reestruturação", "reembolso"]
  },
  {
    "numero": "26",
    "nome": "Apresentação das Demonstrações Contábeis",
    "ativo": true,
    "pdf": "./pdf/CPC-26-R1-Apresentacao-Demonstracoes-Contabeis.pdf",
    "resumo": "./resumos/cpc26-resumo.html",
    "mapa": "./mapas/cpc26-mapa.html",
    "casos": "./casos/cpc26-casos.html",
    "dicionario": "./resumos/cpc26-dicionario.html",
    "flashcards": "./resumos/cpc26-flashcards.html",
    "quizzes": "./quizzes/cpc26-index.html",
    "comentarios": "./comentarios/cpc26-questoes.html",
    "banco": "./questoes/cpc26-banco.html",
    "simulado": "./quizzes/cpc26-simulado.html",
    "macetes": "./resumos/cpc26-macetes.html",
    "erros": "./resumos/cpc26-erros.html",
    "checklist": "./resumos/cpc26-checklist.html",
    "palavras": ["demonstrações contábeis", "balanço patrimonial", "dre", "dra", "dmpl", "notas explicativas", "materialidade", "continuidade", "comparativos"]
  },
  {
    "numero": "27",
    "nome": "Ativo Imobilizado",
    "ativo": true,
    "pdf": "./pdf/CPC-27-Ativo-Imobilizado.pdf",
    "resumo": "./resumos/cpc27-resumo.html",
    "mapa": "./mapas/cpc27-mapa.html",
    "casos": "./casos/cpc27-casos.html",
    "dicionario": "./resumos/cpc27-dicionario.html",
    "flashcards": "./resumos/cpc27-flashcards.html",
    "quizzes": "./quizzes/cpc27-index.html",
    "comentarios": "./comentarios/cpc27-questoes.html",
    "banco": "./questoes/cpc27-banco.html",
    "simulado": "./quizzes/cpc27-simulado.html",
    "macetes": "./resumos/cpc27-macetes.html",
    "erros": "./resumos/cpc27-erros.html",
    "checklist": "./resumos/cpc27-checklist.html",
    "palavras": ["ativo imobilizado", "depreciação", "vida útil", "valor residual", "componentização", "custo", "impairment", "baixa"]
  },
  {
    "numero": "31",
    "nome": "Ativo Não Circulante Mantido para Venda e Operação Descontinuada",
    "ativo": true,
    "pdf": "./pdf/CPC-31-Ativo-Nao-Circulante-Mantido-para-Venda.pdf",
    "resumo": "./resumos/cpc31-resumo.html",
    "mapa": "./mapas/cpc31-mapa.html",
    "casos": "./casos/cpc31-casos.html",
    "dicionario": "./resumos/cpc31-dicionario.html",
    "flashcards": "./resumos/cpc31-flashcards.html",
    "quizzes": "./quizzes/cpc31-index.html",
    "comentarios": "./comentarios/cpc31-questoes.html",
    "banco": "./questoes/cpc31-banco.html",
    "simulado": "./quizzes/cpc31-simulado.html",
    "macetes": "./resumos/cpc31-macetes.html",
    "erros": "./resumos/cpc31-erros.html",
    "checklist": "./resumos/cpc31-checklist.html",
    "palavras": ["mantido para venda", "operação descontinuada", "grupo para alienação", "valor justo menos despesas", "depreciação", "ativo circulante"]
  },
  {
    "numero": "32",
    "nome": "Tributos sobre o Lucro",
    "ativo": true,
    "pdf": "./pdf/CPC-32-Tributos-sobre-o-Lucro.pdf",
    "resumo": "./resumos/cpc32-resumo.html",
    "mapa": "./mapas/cpc32-mapa.html",
    "casos": "./casos/cpc32-casos.html",
    "dicionario": "./resumos/cpc32-dicionario.html",
    "flashcards": "./resumos/cpc32-flashcards.html",
    "quizzes": "./quizzes/cpc32-index.html",
    "comentarios": "./comentarios/cpc32-questoes.html",
    "banco": "./questoes/cpc32-banco.html",
    "simulado": "./quizzes/cpc32-simulado.html",
    "macetes": "./resumos/cpc32-macetes.html",
    "erros": "./resumos/cpc32-erros.html",
    "checklist": "./resumos/cpc32-checklist.html",
    "palavras": ["tributos sobre o lucro", "tributo corrente", "tributo diferido", "base fiscal", "diferença temporária", "ativo fiscal diferido", "passivo fiscal diferido", "prejuízo fiscal", "Pilar Dois"]
  },
  {
    "numero": "36",
    "nome": "Demonstrações Consolidadas",
    "palavras": [
      "consolidação",
      "controladora",
      "controlada"
    ]
  },
  {
    "numero": "45",
    "nome": "Divulgação de Participações em Outras Entidades",
    "palavras": [
      "participações",
      "divulgação",
      "outras entidades"
    ]
  },
  {
    "numero": "46",
    "nome": "Mensuração do Valor Justo",
    "palavras": [
      "valor justo",
      "hierarquia",
      "mensuração"
    ]
  },
  {
    "numero": "47",
    "nome": "Receita de Contrato com Cliente",
    "palavras": [
      "receita",
      "contrato",
      "cliente",
      "obrigação de desempenho"
    ]
  },
  {
    "numero": "48",
    "nome": "Instrumentos Financeiros",
    "palavras": [
      "instrumentos financeiros",
      "perda esperada",
      "classificação"
    ]
  },
  {
    "numero": "28",
    "nome": "Propriedade para Investimento",
    "ativo": true,
    "pdf": "./pdf/CPC-28-Propriedade-para-Investimento.pdf",
    "resumo": "./resumos/cpc28-resumo.html",
    "mapa": "./mapas/cpc28-mapa.html",
    "casos": "./casos/cpc28-casos.html",
    "dicionario": "./resumos/cpc28-dicionario.html",
    "flashcards": "./resumos/cpc28-flashcards.html",
    "quizzes": "./quizzes/cpc28-index.html",
    "comentarios": "./comentarios/cpc28-questoes.html",
    "banco": "./questoes/cpc28-banco.html",
    "simulado": "./quizzes/cpc28-simulado.html",
    "macetes": "./resumos/cpc28-macetes.html",
    "erros": "./resumos/cpc28-erros.html",
    "checklist": "./resumos/cpc28-checklist.html",
    "palavras": ["propriedade para investimento", "valor justo", "aluguel", "valorização", "transferência", "imóvel", "método do custo"]
  }
];
